### ISSUE TITLE
未完成？还是不兼容 node v0.12.0？错误：SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by cos800** [xiaoshan5733/dingtalk-node#1]
```
% node initDingtalk
/Users/myName/myProj/node_modules/dingtalk-node/node_modules/qs/lib/index.js:5
const Stringify = require('./stringify');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/myName/myProj/node_modules/dingtalk-node/index.js:2:10)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

**Comment by cos800** [comment]
重新安装了一下 确实发现有警告：

```
WARN engine qs@6.0.1: wanted: {"node":">=4.0.0"} (current: {"node":"0.12.0","npm":"2.14.14"})
```

**Comment by wengqianshan** [comment]
@cos800  nodejs版本低了不支持ES6语法，建议升级到最新版啊

**Comment by cos800** [comment]
嗯 已解决
